name: chime
services:
  app:
    image: ghcr.io/m1sk9/chime:v0.3.0
    environment:
      CHIME_CONFIG: /etc/chime/config.toml
    volumes:
      - /home/m1sk9/chime-data/config.toml:/etc/chime/config.toml:ro
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "/usr/local/bin/chime", "health"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
