name: babyrite
services:
  app:
    image: ghcr.io/m1sk9/babyrite:v1.4.0
    volumes:
      - /home/m1sk9/babyrite-data/config.toml:/config/config.toml:ro
    env_file:
      - .env
    restart: always
