services:
  kavita:
    image: jvmilazz0/kavita:0.8.6    # Using the stable branch from the official dockerhub repo.
    container_name: kavita
    volumes:
        - /home/m1sk9/kavita-data:/kavita/config
        - /home/m1sk9/otaku/books:/books
        - /home/m1sk9/otaku/images:/images
    environment:
        - TZ=Asia/Tokyo
        - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
    ports:
        - "5000:5000"
    restart: unless-stopped
