name: honeypot
services:
  app:
    image: ghcr.io/m1sk9/honeypot:v0.2.0
    volumes:
      - /home/m1sk9/honeypot-data/config.toml:/config/config.toml:ro
    env_file:
      - .env
    restart: always
