name: CI docs

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    working-directory: ./docs

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Setup Development Environment
        uses: jdx/mise-action@v2

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          pnpm install

      - name: Lint site
        run: |
          pnpm lint

      - name: Check format
        run: |
          pnpm check:format

      - name: Build site
        run: |
          pnpm build
