name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-compose:
    name: Test compose files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Testing compose files
        run: |
          for dir in $(find . -name 'compose.yaml' -exec dirname {} docker;)
          do
              echo "Testing docker compose in $dir"
              cd $dir
              touch .env
              docker compose config
              cd -
          done
