services:
  vw:
    image: vaultwarden/server:1.34.2
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /home/m1sk9/vw-data/:/data/
    # Vaultwarden must connect to Tailnet deployed on Tailscale to use it.
    ports:
      - 127.0.0.1:8080:80
